<a href="https://colab.research.google.com/github/phanconghieu29/Artificial_Intelligence/blob/main/Buoi1_Gioithieu_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Bai 13
a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]
min = len(a) if len(a) < len(b) else len(a)
c = a if len(a) > len(b) else b
for i in range(min):
  c[i] = a[i] + b[i]
print(c)

[5, 16, 5, 7, 2, 8]


In [3]:
#Bai 14
#a) Tao mang 2 chieu chua so nguyen ngau nhien
import numpy as np
m = int(input("Nhap so dong: "))
n = int(input("Nhap so cot: "))
a = np.random.randint(-10, 10, (m,n))
print(a)
#b) Xuat cac phan tu thuoc dong K
k = int(input("Nhap dong k: "))
if(k < m and k >= 0):
  print(a[k])
else:
  print("Dong k khong co trong mang")
#c) Xuat cac phan tu thuoc cot L
l = int(input("Nhap dong l: "))
if(l < n and l >= 0):
  for i in range(m):
    print(a[i][l])
else:
  print("Dong l khong co trong mang")

Nhap so dong: 3
Nhap so cot: 4
[[ 7 -1 -6 -4]
 [ 6  7  0  1]
 [ 1  0  8  2]]
Nhap dong k: 1
[6 7 0 1]
Nhap dong l: 2
-6
0
8


In [4]:
#Bai 15
#a) Xay dung cau truc Sinh Vien
class SinhVien:
  dict_sv = {
      "MSSV": [],
      "TenSV": [],
      "NamSinh": [],
      "DiemTB": []
  }
#b) Tao mang cho n sinh vien
  def __init__(self, n):
    for i in range(n):
      ma = input("Nhap ma sinh vien: ")
      ten = input("Nhap ten sinh vien: ")
      ns = input("Nhap nam sinh: ")
      dtb = input("Nhap diem trung binh: ")
      self.dict_sv["MSSV"].append(ma)
      self.dict_sv["TenSV"].append(ten)
      self.dict_sv["NamSinh"].append(ns)
      self.dict_sv["DiemTB"].append(dtb)
#c) Cho biet co bao nhieu sinh vien du dieu kien len lop
def dem_SV_Duoc_Len_Lop():
  count = 0
  for i in range(len(SinhVien.dict_sv["MSSV"])):
    if float(SinhVien.dict_sv["DiemTB"][i]) >= 5:
      count += 1
  return count

SinhVien(3)
print("So sinh vien du dieu kien len lop la: " + str(dem_SV_Duoc_Len_Lop()))

Nhap ma sinh vien: 1
Nhap ten sinh vien: A
Nhap nam sinh: 2003
Nhap diem trung binh: 7
Nhap ma sinh vien: 2
Nhap ten sinh vien: B
Nhap nam sinh: 2003
Nhap diem trung binh: 4
Nhap ma sinh vien: 3
Nhap ten sinh vien: C
Nhap nam sinh: 2003
Nhap diem trung binh: 8
So sinh vien du dieu kien len lop la: 2
